name: 'Artifact Comment Action'
description: 'Comment artifacts generated in pull requests.'

branding:
  icon: 'package'
  color: 'red'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication'
    required: true
  repo_owner:
    description: 'The owner of the repository'
    required: false
  repo_name:
    description: 'The name of the repository'
    required: false
  run_id:
    description: 'The ID number of the workflow run'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
